### ISSUE TITLE
ManyItems type issue

### ISSUE THREAD

**Issue by aurelienbobenrieth** [directus/sdk#146] opened 2023-05-04 17:56 UTC
### Describe the Bug

Inside `@directus/sdk` type definitions we can find that:
```typescript
readByQuery<Q extends QueryMany<T>>(query?: Q, options?: ItemsOptions): Promise<ManyItems<T, Q>>;
```

and that:
```typescript
declare type ManyItems<T extends Item, Q extends QueryMany<T> = Record<string, any>> = {
    data?: NonNullable<OneItem<T, Q>>[] | null;
    meta?: ItemMetadata;
```
    
**However:**
```typescript
await directus.items(/* ... */).readByQuery( /* ... */).data
```
is **never** an array. Which makes typescript trigger errors inside my codebase whereas there are none.

**The type should be:**
```typescript
data?: NonNullable<OneItem<T, Q>> | null;`
```
**For example:**
```typescript
await directus.items('footer').readByQuery({})
```
**returns**
```json
{ 
  "data": {
    "slug": "default-footer",
    "navigations": [ 1, 2, 3, 4, 5 ]
  }
}
```

### To Reproduce

Try to use :
```typescript
const response = await directus.items(/* ... */).readByQuery( /* ... */)
```
wherever in your codebase (with or without `fields` etc) and do a `console.log(response.data)`.

You will see that it is an object, and not an array.

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment] 2023-05-04 18:01
> [...] is **never** an array. 

I don't think that's accurate 🤔 Unless the collection is a singleton, `data` is an array of objects. If the collection is a singleton, you should use `directus.singleton('footer')` instead to get the right type

**Comment by aurelienbobenrieth** [comment] 2023-05-04 18:10
Ah yes ! 

Though, as far as it is my bad for using `.items(/* ... */)` on a singleton, it feels wrong that data is returned as an object rather than an array with a single object. It makes the type definition untruthy.

**Comment by rijkvanzanten** [comment] 2023-05-04 18:35
The type definition can't know that the referenced collection is a singleton ahead of time, so it has to assume that your usage of `.items()` means you're querying a collection of multiple items. Happy to discuss improvements on that setup if you have any :) I'll close this bug for now, as things are technically working as intended.

**Closed by rijkvanzanten** 2023-05-04 18:35 UTC

**Comment by rijkvanzanten** [comment] 2023-05-04 21:26
I think that would be a massive breaking change in the current REST API output, so I don't think that's an easy (nor necessarily wanted!) change to make. We could theoretically wrap the singleton object in an array on the JS SDK side of things, but then the behavior is going to be different between the two. Not sure if that's better or worse!

**Comment by aurelienbobenrieth** [comment] 2023-05-04 21:42
I do not have enough maturity playing with Directus types to have a decent opinion on that so I trust what you say!
I have another questions regarding types, but I will put that on Discord.
Thank you for your fast responses!
